name 'evenup-graphite'
version '3.0.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages graphite.'
description 'Installs, configures, and runs the graphite services'
project_page 'https://github.com/evenup/evenup-graphite'
dependency 'evenup/apache', '>= 1.3.0'
dependency 'ripienaar/concat', '>= 0.2.0'

